### ISSUE TITLE
Dependencies Injection

### ISSUE THREAD

**Issue by dungviettran89** [dungviettran89/go-len-core#1]
As the central core of many frameworks, DI is crucial to build a stable and easy to extend framework. We need to select the best DI right now as the base of the new framework.
1. Evaluate a set of DI tools (alice, dig, fx, wire)
2. Build a new API based on the best tools (maybe borrow some form Spring)
3. Build a wrapper for easier switching later

**Comment by kiennt23** [comment]
Bellow is comparison between DI frameworks in golang.
1. Alice tag is not nice.
2. Facebook’s inject is no longer maintained.
3. Uber’s dig is a full featured reflection based DI framework. It resolves dependencies at runtime. Easy to extend.
4. Google’s wire is a compile time DI framework. It has advantages: better runtime, easier to debug.

Since the purpose of our wrapper is to provide a Spring liked framework, I suggest we go with Uber’s dig. If we choose to use wire then we have to extend a lot of code generation here.

**Comment by dungviettran89** [comment]
Decided to use Uber dig after discussion.
Now we need to build an wrapper for easier switching to anther DI.

**Comment by kiennt23** [comment]
To decide which features we to support in the core library.

**Comment by kiennt23** [comment]
Move to go-len repository
